{% set sdata = load_setup_py_data() %}

package:
  name: pyviz_comms
  version: {{ sdata['version'] }}

source:
  path: ..

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  host:
    - python >=3.8
    - param
    - pip
    - jupyter-packaging >=0.7.9,<0.8
    - jupyterlab >=4.0,<5
    - notebook
    - hatchling
    - hatch-nodejs-version
    - hatch-jupyter-builder
  run:
    - python >=3.8
    - param
  run_constrained:
    - jupyterlab >=4.0,<5

test:
  imports:
    - pyviz_comms

about:
  home: https://www.holoviz.org
  summary: Bidirectional communication for PyViz
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
